version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  reviewers:
  - pcorpet
  - mlendale
  - zozoens31
  - emilieguth
  ignore:
  - dependency-name: pylint
    versions:
    - 2.7.3
    - 2.8.1
  - dependency-name: numpy
    versions:
    - 1.20.0
